#DATAMINING PROJECT V1.0
***From Baptiste Danichert & Ahmed Balibala***

**Last update**: adding new models

**Description:** You have noticed that to improve one’s skills in a new foreign language, it is important to read texts in that language. These texts have to be at the reader’s language level. However, it is difficult to find texts that are close to someone’s knowledge level (A1 to C2). You have decided to build a model for English speakers that predicts the difficulty of a French written text. This can be then used, e.g., in a recommendation system, to recommend texts, e.g, recent news articles that are appropriate for someone’s language level. If someone is at A1 French level, it is inappropriate to present a text at B2 level, as she won’t be able to understand it. Ideally, a text should have many known words and may have a few words that are unknown so that the person can improve.



# 1. Loading the training data

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/BapDanSI/DataMiningProject/main/data/training_data.csv')
df_pred = pd.read_csv('https://raw.githubusercontent.com/BapDanSI/DataMiningProject/main/data/unlabelled_test_data.csv')

In [ ]:
df_pred.head()

id                                           sentence
0   0  Nous dûmes nous excuser des propos que nous eû...
1   1  Vous ne pouvez pas savoir le plaisir que j'ai ...
2   2  Et, paradoxalement, boire froid n'est pas la b...
3   3  Ce n'est pas étonnant, car c'est une saison my...
4   4  Le corps de Golo lui-même, d'une essence aussi...

In [ ]:
df.head()

id                                           sentence difficulty
0   0  Les coûts kilométriques réels peuvent diverger...         C1
1   1  Le bleu, c'est ma couleur préférée mais je n'a...         A1
2   2  Le test de niveau en français est sur le site ...         A1
3   3           Est-ce que ton mari est aussi de Boston?         A1
4   4  Dans les écoles de commerce, dans les couloirs...         B1

# 2. Dataframe analysis


In [ ]:
df.shape

(4800, 3)

-> 4800 rows and 2 columns (excluding first column "id")

In [ ]:
df.isnull().sum()

id            0
sentence      0
difficulty    0
dtype: int64

-> no NAs

In [ ]:
df.duplicated(subset="sentence").value_counts()

False    4800
dtype: int64

-> no duplicate in the data

#3.  Baseline

In [ ]:
np.random.seed = 0

In [ ]:
base_rate = max(df.value_counts('difficulty'))/df.shape[0]
print('Base rate:', round(base_rate,4))

Base rate: 0.1694


# 4. Classification Algorithms

Dependent variable (y) is the column named "difficulty".
<br>We split the data into 80% training and 20% test set.


In [ ]:
y = df['difficulty']
X = df['sentence']
X_pred = df_pred['sentence']

### i. Logistic Regression.
We use the following parameters for the LogisticRegressionCV():

* cross-validation to 5 folds
* maximum interation to 1000
* random state to 0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [ ]:
tfidf = TfidfVectorizer(ngram_range=(1, 1))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

classifier = LogisticRegressionCV(solver='lbfgs', cv=5, max_iter=1000, random_state=0)
pl = Pipeline([('vectorizer', tfidf),
                 ('classifier', classifier)])
pl.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('classifier',
                 LogisticRegressionCV(cv=5, max_iter=1000, random_state=0))])

In [ ]:
def evaluate(true, pred):
    precision = precision_score(true, pred,average='macro')
    recall = recall_score(true, pred,average='macro')
    f1 = f1_score(true, pred,average='macro')
    print(f"CONFUSION MATRIX:\n{confusion_matrix(true, pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(true, pred):.4f}")
    print(f"CLASSIFICATION REPORT:\n\tPrecision: {precision:.4f}\n\tRecall: {recall:.4f}\n\tF1_Score: {f1:.4f}")

In [ ]:
y_pred = pl.predict(X_test)
evaluate(y_test, y_pred)

CONFUSION MATRIX:
[[91 34 20  9  4  3]
 [50 62 34  3  5 10]
 [12 35 72 14  7 20]
 [ 6  6 18 67 24 23]
 [ 3  5 13 40 65 47]
 [ 7  6  9 16 23 97]]
ACCURACY SCORE:
0.4729
CLASSIFICATION REPORT:
	Precision: 0.4723
	Recall: 0.4747
	F1_Score: 0.4703


In [ ]:
predict = pl.predict(X_pred)

In [ ]:
submission= pd.DataFrame()
submission['id']= df_pred.index
submission['difficulty'] = predict

In [ ]:
submission.to_csv("submission.csv", index=False)

### ii. kNNeighbours

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

grid = {'n_neighbors':np.arange(1,100),
        'p':np.arange(1,3),
        'weights':['uniform','distance']}

knn = KNeighborsClassifier()
classifier_knn = GridSearchCV(knn, grid, cv=5)

pl_knn = Pipeline([('vectorizer', tfidf),
                 ('classifier', classifier_knn)])

pl_knn.fit(X_train, y_train)

print("Hyperparameters:", classifier_knn.best_params_)

Hyperparameters: {'n_neighbors': 63, 'p': 2, 'weights': 'distance'}


In [ ]:
y_knn_predict = pl_knn.predict(X_test)
evaluate(y_test, y_knn_predict)

CONFUSION MATRIX:
[[105  36  13   0   1   6]
 [ 83  59  19   0   0   3]
 [ 60  48  37   3   1  11]
 [ 18  24  22  32  12  36]
 [ 14  19  29  22  20  69]
 [ 18  20  10  10   7  93]]
ACCURACY SCORE:
0.3604
CLASSIFICATION REPORT:
	Precision: 0.3859
	Recall: 0.3616
	F1_Score: 0.3361


In [ ]:
knn_predict = pl_knn.predict(X_pred)
submission_knn= pd.DataFrame()
submission_knn['id']= df_pred.index
submission_knn['difficulty'] = knn_predict
submission_knn.to_csv("submissionknn.csv", index=False)

###  iii. Decision Trees

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
pl_dtc = Pipeline([('vectorizer', tfidf),
                 ('classifier', dtc)])
pl_dtc.fit(X_train, y_train)
y_pred_dtc = pl_dtc.predict(X_test)

evaluate(y_test, y_pred_dtc)

CONFUSION MATRIX:
[[79 34 28  9  6  5]
 [46 57 35 16  4  6]
 [29 42 36 20 16 17]
 [ 9 17 30 42 26 20]
 [ 9 16 35 42 38 33]
 [11 10 30 37 33 37]]
ACCURACY SCORE:
0.3010
CLASSIFICATION REPORT:
	Precision: 0.3028
	Recall: 0.3015
	F1_Score: 0.2990


In [ ]:
dtc_predict = pl_dtc.predict(X_pred)
submission_dtc= pd.DataFrame()
submission_dtc['id']= df_pred.index
submission_dtc['difficulty'] = dtc_predict
submission_dtc.to_csv("submissiondtc.csv", index=False)

### iv. Random Forest Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
pl_rfc = Pipeline([('vectorizer', tfidf),
                 ('classifier', rfc)])

pl_rfc.fit(X_train, y_train)

y_pred_rfc = pl_rfc.predict(X_test)

evaluate(y_test, y_pred_rfc)

CONFUSION MATRIX:
[[129  15   9   5   2   1]
 [ 79  48  26   7   4   0]
 [ 41  37  52  16  11   3]
 [ 17  12  15  64  24  12]
 [ 18   8  26  50  47  24]
 [ 22   6  14  36  28  52]]
ACCURACY SCORE:
0.4083
CLASSIFICATION REPORT:
	Precision: 0.4164
	Recall: 0.4107
	F1_Score: 0.3944


In [ ]:
rfc_predict = pl_rfc.predict(X_pred)
submission_rfc= pd.DataFrame()
submission_rfc['id']= df_pred.index
submission_rfc['difficulty'] = rfc_predict
submission_rfc.to_csv("submissionrfc.csv", index=False)

### v. Support Vector Classifier

In [ ]:
from sklearn.svm import SVC

svc = SVC()
pl_svc = Pipeline([('vectorizer', tfidf),
                 ('classifier', svc)])

pl_svc.fit(X_train, y_train)

y_pred_svc = pl_svc.predict(X_test)

evaluate(y_test, y_pred_svc)

CONFUSION MATRIX:
[[89 30 25 13  3  1]
 [46 68 30  8  6  6]
 [ 9 38 68 21  9 15]
 [ 6  4 13 74 23 24]
 [ 2  2 16 52 63 38]
 [ 6  6  8 26 25 87]]
ACCURACY SCORE:
0.4677
CLASSIFICATION REPORT:
	Precision: 0.4711
	Recall: 0.4702
	F1_Score: 0.4671


In [ ]:
svc_predict = pl_svc.predict(X_pred)
submission_svc= pd.DataFrame()
submission_svc['id']= df_pred.index
submission_svc['difficulty'] = svc_predict
submission_svc.to_csv("submissionsvc.csv", index=False)

###vi. AdaBoostClassifier

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

abc = AdaBoostClassifier()
pl_abc = Pipeline([('vectorizer', tfidf),
                 ('classifier', abc)])

pl_abc.fit(X_train, y_train)

y_pred_abc = pl_abc.predict(X_test)

evaluate(y_test, y_pred_abc)

CONFUSION MATRIX:
[[69 50 18 21  1  2]
 [48 62 25 21  5  3]
 [22 45 40 27 22  4]
 [ 7 11  9 60 39 18]
 [ 5  8 23 54 66 17]
 [10  9 10 41 58 30]]
ACCURACY SCORE:
0.3406
CLASSIFICATION REPORT:
	Precision: 0.3504
	Recall: 0.3408
	F1_Score: 0.3353


###vii. MLPC Classifier

In [ ]:
from sklearn.neural_network import MLPClassifier

mlpc = MLPClassifier()
pl_mlpc = Pipeline([('vectorizer', tfidf),
                 ('classifier', mlpc)])

pl_mlpc.fit(X_train, y_train)

y_pred_mlpc = pl_mlpc.predict(X_test)

evaluate(y_test, y_pred_mlpc)

CONFUSION MATRIX:
[[93 47 17  2  0  2]
 [59 72 26  3  2  2]
 [19 41 74  8  5 13]
 [13 16 27 50 23 15]
 [10 17 15 40 60 31]
 [16 12 22 18 21 69]]
ACCURACY SCORE:
0.4354
CLASSIFICATION REPORT:
	Precision: 0.4466
	Recall: 0.4350
	F1_Score: 0.4336


In [ ]:
mlpc_predict = pl_mlpc.predict(X_pred)
submission_mlpc= pd.DataFrame()
submission_mlpc['id']= df_pred.index
submission_mlpc['difficulty'] = mlpc_predict
submission_mlpc.to_csv("submissionmlpc.csv", index=False)

#5. Comparing the models

In [1]:
import pandas as pd

df_comparison = pd.DataFrame(columns=['Model_Name', 'Base_Rate', 'Precisions','Recall','F1-Score', 'Accuracy'])


df_comparison['Model_Name'] = ['Logistic Reg', 'KNN', 'Tree', 'Random Forest', 'Support Vector', 'AdaBooster', 'MLPC']
df_comparison['Base_Rate'] = ['0.1694', '0.1694', '0.1694', '0.1694', '0.1694', '0.1694', '0.1694']
df_comparison['Precisions'] = ['0.4723', '0.3859', '0.3028','0.4164', '0.4711', '0.3504', '0.4466']
df_comparison['Recall'] = ['0.4747', '0.3616', '0.3015','0.4107', '0.4702', '0.3408', '0.4350']
df_comparison['F1-Score'] = ['0.4703', '0.3361', '0.2990','0.3944', '0.4671', '0.3353', '0.4336']
df_comparison['Accuracy'] = ['0.4729', '0.3604', '0.3010','0.4083', '0.4677', '0.3406', '0.4354']


df_comparison

Model_Name Base_Rate Precisions  Recall F1-Score Accuracy
0    Logistic Reg    0.1694     0.4723  0.4747   0.4703   0.4729
1             KNN    0.1694     0.3859  0.3616   0.3361   0.3604
2            Tree    0.1694     0.3028  0.3015   0.2990   0.3010
3   Random Forest    0.1694     0.4164  0.4107   0.3944   0.4083
4  Support Vector    0.1694     0.4711  0.4702   0.4671   0.4677
5      AdaBooster    0.1694     0.3504  0.3408   0.3353   0.3406
6            MLPC    0.1694     0.4466  0.4350   0.4336   0.4354